exports.BILL_TYPE_KEY_MAP = {
  motor_vehicle_sale_invoice: 'vehicle_invoice_total_price_digits',
  used_car_purchase_invoice: 'vehicle_invoice_total_price_digits',
  vat_roll_invoice: 'total_money',
  vehicle_toll: 'money',
  quota_invoice: 'money_small',
  taxi_ticket: 'sum',
  air_transport: 'total',
  train_ticket: 'price',
  general_machine_invoice: 'money',
  shipping_invoice: 'money',
  highway_passenger_invoice: 'money',
  passenger_transport_invoice: 'money',
  parking_invoice: 'money',
  vat_invoice_sales_list: 'total',
  shop_receipt: 'money',
  medical_receipt: 'amount_small',
  travel_transport: 'total_money',
  non_tax_income_unified_bill: 'TotalAmount',
}